### ISSUE TITLE
REST API Authentication

### ISSUE THREAD

**Issue by tomjn** [Automattic/vip-hash#9]
The current implementation has no authentication process. Instead, it should authenticate with the .com API

I've come to the conclusion that building undocumented .com endpoints limits the usefulness of the code and sharing to the VIP team and a8c, as well as becoming dependent on stability and maintenance from .com, and the limitations for iteration that involves

This will likely involve the need for a new cli subcommand for the auth tokens needed to authenticate

**Comment by Tarendai** [comment]
Should be implemented by #20 once merged

**Comment by tomjn** [comment]
I'm inclined now to use oauth1 instead. Mainly as it's simpler to use. The OAuth 2 REST support is a premium plugin with a free version, whereas the OAuth1 plugin was made by the same people as WP API, is much smaller, and has a CLI command example

**Comment by tomjn** [comment]
*Update!*

The OAuth branch now makes use of OAuth1a to authenticate, but it has an issue regarding the remotes table, and it needs to change how it makes requests in the sync command to use said authentication

Specifically, the new columns in the remotes table mean a table schema change is necessary, but I only ever got round to implementing that functionality for changes to the hashes table. I've put in a new `upgrade` command to trigger it from CLI without code changes, and adjusted the class. It just needs implementing in the `copy_remotes_table` method of the PDO DB Helper class

Once this is done, authenticating with a remote should be implemented, and the `sync` command can be updated to use said auth details, which should be easy. I removed guzzle and some other dependencies and switched to the Requests library by Ryan McCue.

Also, I think for the moment, re-authentication can be done by removing and re-adding a remote, so the remote removal needs implementing, but that shouldn't be hard

**Comment by tomjn** [comment]
Now the oauth branch is merged I think we can call this implemented, pending further tests
